const detail = {
    avatar: "http://hinhnendephd.com/wp-content/uploads/2019/10/anh-avatar-dep.jpg",
    email: "scb@gmail.com",
    name: "SCB",
    phone: "0123456789",
}

const listUser = [
    {
        user_id: 1,
        user_email: "user1@gmail.com",
        user_mobile: "0123456781",
        user_permission_name: "admin",
        user_permission_id: 1,
        user_username: "user1",
    },
    {
        user_id: 2,
        user_email: "user2@gmail.com",
        user_mobile: "0123456782",
        user_permission_name: "người dùng",
        user_permission_id: 2,
        user_username: "user2",
    },
    {
        user_id: 3,
        user_email: "user3@gmail.com",
        user_mobile: "0123456783",
        user_permission_name: "người dùng",
        user_permission_id: 2,
        user_username: "user3",
    },
    {
        user_id: 4,
        user_email: "user4@gmail.com",
        user_mobile: "0123456784",
        user_permission_name: "người dùng",
        user_permission_id: 2,
        user_username: "user4",
    },
    {
        user_id: 5,
        user_email: "user5@gmail.com",
        user_mobile: "0123456785",
        user_permission_name: "người dùng",
        user_permission_id: 2,
        user_username: "user5",
    },
    {
        user_id: 6,
        user_email: "user6@gmail.com",
        user_mobile: "0123456786",
        user_permission_name: "admin",
        user_permission_id: 1,
        user_username: "user6",
    },
    {
        user_id: 7,
        user_email: "user7@gmail.com",
        user_mobile: "0123456787",
        user_permission_name: "admin",
        user_permission_id: 1,
        user_username: "user7",
    },
    {
        user_id: 8,
        user_email: "user8@gmail.com",
        user_mobile: "0123456788",
        user_permission_name: "người dùng",
        user_permission_id: 2,
        user_username: "user8",
    },

    {
        user_id: 9,
        user_email: "user9@gmail.com",
        user_mobile: "0123456789",
        user_permission_name: "admin",
        user_permission_id: 1,
        user_username: "user9",
    },
    {
        user_id: 10,
        user_email: "user10@gmail.com",
        user_mobile: "0123456790",
        user_permission_name: "người dùng",
        user_permission_id: 2,
        user_username: "user10",
    },
    {
        user_id: 11,
        user_email: "user11@gmail.com",
        user_mobile: "0123456791",
        user_permission_name: "người dùng",
        user_permission_id: 2,
        user_username: "user11",
    },
    {
        user_id: 12,
        user_email: "user12@gmail.com",
        user_mobile: "0123456792",
        user_permission_name: "người dùng",
        user_permission_id: 2,
        user_username: "user12",
    },
    {
        user_id: 13,
        user_email: "user13@gmail.com",
        user_mobile: "0123456793",
        user_permission_name: "người dùng",
        user_permission_id: 2,
        user_username: "user13",
    },
    {
        user_id: 14,
        user_email: "user14@gmail.com",
        user_mobile: "0123456794",
        user_permission_name: "người dùng",
        user_permission_id: 2,
        user_username: "user14",
    },
    {
        user_id: 15,
        user_email: "user15@gmail.com",
        user_mobile: "0123456715",
        user_permission_name: "người dùng",
        user_permission_id: 2,
        user_username: "user15",
    },
    {
        user_id: 16,
        user_email: "user16@gmail.com",
        user_mobile: "0123456716",
        user_permission_name: "người dùng",
        user_permission_id: 2,
        user_username: "user16",
    },
    {
        user_id: 17,
        user_email: "user17@gmail.com",
        user_mobile: "0123456797",
        user_permission_name: "người dùng",
        user_permission_id: 2,
        user_username: "user17",
    },
    {
        user_id: 18,
        user_email: "user18@gmail.com",
        user_mobile: "0123456798",
        user_permission_name: "admin",
        user_permission_id: 1,
        user_username: "user18",
    },
    {
        user_id: 19,
        user_email: "user19@gmail.com",
        user_mobile: "0123456799",
        user_permission_name: "admin",
        user_permission_id: 1,
        user_username: "user19",
    },
    {
        user_id: 20,
        user_email: "user20@gmail.com",
        user_mobile: "0123456800",
        user_permission_name: "người dùng",
        user_permission_id: 2,
        user_username: "user20",
    },
    {
        user_id: 21,
        user_email: "user21@gmail.com",
        user_mobile: "0123456801",
        user_permission_name: "người dùng",
        user_permission_id: 2,
        user_username: "user21",
    }, {
        user_id: 22,
        user_email: "user22@gmail.com",
        user_mobile: "0123456802",
        user_permission_name: "người dùng",
        user_permission_id: 2,
        user_username: "user2",
    },
]

module.exports = {
    listUser,
    detail
}